prefix=${PKG_CONFIG_PREFIX}
exec_prefix=${PKG_CONFIG_EXEC_PREFIX}
libdir=${PKG_CONFIG_LIBDIR}
includedir=${PKG_CONFIG_INCLUDEDIR}
datarootdir=${PKG_CONFIG_DATAROOTDIR}
pkgdatarootdir=${PKG_CONFIG_PKGDATAROOTDIR}
docdir=${PKG_CONFIG_DOCDIR}
doxygendocdir=${PKG_CONFIG_DOXYGENDOCDIR}

Name: ${PLUGIN_NAME}
Description: ${PLUGIN_DESCRIPTION}
URL: ${PKG_CONFIG_URL}
Version: ${PKG_CONFIG_VERSION}
Requires: ${PKG_CONFIG_REQUIRES}
Conflicts: 
Libs: ${PLUGIN_LIBS}
Cflags: ${PLUGIN_CFLAGS}

